homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: 1
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include components/customize.yaml
  auth_providers:
   - type: homeassistant
  #  - type: legacy_api_password
frontend:
  themes: !include components/themes.yaml
  javascript_version: latest
config:
updater:
  include_used_components: true
discovery:
conversation:
history:
logbook:
  exclude:
    entities:
    - sensor.weather_condition
    - sensor.weather_detailed_condition
    - sensor.weather_humidity
    - sensor.weather_precipitation
    - sensor.weather_stationname
    - sensor.weather_symbol
    - sensor.weather_temperature
    - sensor.weather_wind_direction
    - sensor.weather_wind_force
    - weather.voorschoten
map:
sun:
system_health:
person:
wake_on_lan:

http:
  base_url: https://home.eavv.nl
  # api_password: !secret api_password

api:
python_script:

### iframes
panel_iframe:
  nodered:
    title: Node-RED
    icon: mdi:sitemap
    url: http://homeserver:1880
  pihole:
    title: Pi-Hole
    icon: mdi:cancel
    url: http://homeserver:4865/admin/index.php
  vscode:
    title: VS Code
    icon: mdi:visual-studio-code
    url: http://homeserver:1337

### included components, automations and scripts
sensor: !include components/sensors.yaml
notify: !include components/notifyers.yaml
group: !include components/groups.yaml
switch: !include components/switches.yaml
automation: !include_dir_merge_list automations
script: !include scripts/scripts.yaml
media_player: !include components/mediaplayers.yaml
cover: !include components/covers.yaml
zone: !include components/zones.yaml
cloud: !include components/cloud.yaml
timer: !include components/timers.yaml

input_boolean:
  tomato_flow:
    name: Tomato Flow
    icon: mdi:food-apple

### direct components
weather:
  - platform: buienradar
    name: Voorschoten
    forecast: True
    latitude: !secret lat
    longitude: !secret long

device_tracker:
  - platform: unifi
    host: !secret host_ip
    site_id: 5vyjbuzt
    verify_ssl: false
    username: !secret unifi_user
    password: !secret unifi_pass
    consider_home: 120
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false
    ssid_filter:
      - 'WEFi'

# Text to speech
tts:
  - platform: microsoft
    api_key: !secret speech_api_key
    language: en-us
    gender: Female
    type: JessaRUS
    rate: 20
    volume: -50
    pitch: high
    contour: (0, 0) (100, 100)

hue:
  bridges:
    - host: !secret hue_ip

sabnzbd:
  host: !secret host_ip
  port: !secret sab_port
  api_key: !secret sab_api_key
  sensors:
    - 'current_status'
    - 'speed'
    - 'queue_size'
    - 'queue_remaining'
    - 'disk_size'
    - 'disk_free'

sonos:
  media_player:
    hosts: 
      - !secret sonos_playbase_ip
      - !secret sonos_kitchen_front_ip
      - !secret sonos_study_ip
      # - !secret sonos_kitchen_back_ip
      # - !secret sonos_living_front_ip
      # - !secret sonos_living_back_ip

ring:
  username: !secret ring_username
  password: !secret ring_password

binary_sensor:
  - platform: ring
camera:
  - platform: ring
  
# homeconnect:
#   client_id: !secret homeconnect_client_id
#   client_secret: !secret homeconnect_client_secret

# logger:
#   default: warning
#   logs:
#     custom_components.homeconnect: debug
#     homeassistant.components.sonos: debug
#     homeassistant.components.media_player.sonos: debug