homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: 1
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include components/customize.yaml
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
frontend:
config:
updater:
  include_used_components: true
discovery:
conversation:
history:
logbook:
  exclude:
    entities:
    - sensor.weather_condition
    - sensor.weather_detailed_condition
    - sensor.weather_humidity
    - sensor.weather_precipitation
    - sensor.weather_stationname
    - sensor.weather_symbol
    - sensor.weather_temperature
    - sensor.weather_wind_direction
    - sensor.weather_wind_force
    - weather.voorschoten
map:
sun:
system_health:
person:
wake_on_lan:

http:
  base_url: https://home.eavv.nl
  api_password: !secret api_password

api:

### included components, automations and scripts
sensor: !include components/sensors.yaml
notify: !include components/notifyers.yaml
group: !include components/groups.yaml
switch: !include components/switches.yaml
automation: !include_dir_merge_list automation
script: !include_dir_merge_list scripts
media_player: !include components/mediaplayers.yaml
zone: !include components/zones.yaml
cloud: !include components/cloud.yaml

### direct components
weather:
  - platform: buienradar
    name: Voorschoten
    forecast: True
    latitude: !secret lat
    longitude: !secret long

device_tracker:
  - platform: unifi
    host: !secret host_ip
    site_id: 5vyjbuzt
    verify_ssl: false
    username: !secret unifi_user
    password: !secret unifi_pass
    consider_home: 120
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false
    ssid_filter:
      - 'WEFi'

# Text to speech
tts:
  - platform: microsoft
    api_key: !secret speech_api_key
    language: en-us
    gender: Female
    type: JessaRUS
    rate: 20
    volume: -50
    pitch: high
    contour: (0, 0) (100, 100)

hue:
  bridges:
    - host: !secret hue_ip

sabnzbd:
  host: !secret host_ip
  port: !secret sab_port
  api_key: !secret sab_api_key
  sensors:
    - 'current_status'
    - 'speed'
    - 'queue_size'
    - 'queue_remaining'
    - 'disk_size'
    - 'disk_free'

sonos:
  media_player:
    hosts: 
      - !secret sonos_playbase_ip
      - !secret sonos_kitchen_front_ip
      # - !secret sonos_kitchen_back_ip
      # - !secret sonos_living_front_ip
      # - !secret sonos_living_back_ip

logger:
  default: warning
  logs:
    custom_components.media_player.xbox: debug
#     homeassistant.components.sonos: debug
#     homeassistant.components.media_player.sonos: debug