homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: 1
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include components/customize.yaml
  auth_providers:
   - type: homeassistant
  #  - type: legacy_api_password
frontend:
  themes: !include components/themes.yaml
  javascript_version: latest
config:
updater:
  include_used_components: true
discovery:
conversation:
recorder:
  db_url: !secret maria_db_url
  purge_keep_days: 60
history:
# azure_event_hub:
#   event_hub_namespace: !secret eh_sas_ns
#   event_hub_instance_name:  !secret eh_sas_instance
#   event_hub_sas_policy: !secret eh_sas_policy
#   event_hub_sas_key: !secret eh_sas_key
#   filter:
#     include_domains:
#     - homeassistant
#     - light
#     - media_player

# azure_event_hub_new:
#   event_hub_namespace: !secret eh_sas_ns
#   event_hub_instance_name:  !secret eh_sas_instance
#   event_hub_sas_policy: !secret eh_sas_policy
#   event_hub_sas_key: !secret eh_sas_key
  # filter:
  #   include_domains:
  #   - homeassistant
  #   - light
  #   - media_player

logbook:
  exclude:
    entities:
    - sensor.weather_condition
    - sensor.weather_detailed_condition
    - sensor.weather_humidity
    - sensor.weather_precipitation
    - sensor.weather_stationname
    - sensor.weather_symbol
    - sensor.weather_temperature
    - sensor.weather_wind_direction
    - sensor.weather_wind_force
    - weather.voorschoten
map:
sun:
system_health:
person:
wake_on_lan:
ffmpeg:
mobile_app:

http:
  base_url: https://ha.eavv.nl
  ssl_certificate: /ssl/fullchain1.pem
  ssl_key: /ssl/privkey1.pem
  use_x_forwarded_for: true
  trusted_proxies: !secret host_ip

api:
python_script:
custom_updater:
  track:
    - components
  component_urls:
    - https://raw.githubusercontent.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/master/custom_components.json

### iframes
panel_iframe:
  sonarr:
    title: Sonarr
    icon: mdi:television-classic
    url: !secret sonarr_address
  couchpotato:
    title: Couchpotato
    icon: mdi:filmstrip
    url: !secret cp_address
  zwave2mqtt:
    title: Z-Wave to MQTT
    icon: mdi:z-wave
    url: !secret zwave2mqtt_address

### included components, automations and scripts
sensor: !include components/sensors.yaml
notify: !include components/notifyers.yaml
group: !include components/groups.yaml
switch: !include components/switches.yaml
automation: !include_dir_merge_list automations
script: !include scripts/scripts.yaml
media_player: !include components/mediaplayers.yaml
cover: !include components/covers.yaml
zone: !include components/zones.yaml
cloud: !include components/cloud.yaml
timer: !include components/timers.yaml

input_boolean:
  tomato_flow:
    name: Tomato Flow
    icon: mdi:food-apple

### direct components
weather:
  - platform: buienradar
    name: Voorschoten
    forecast: True
    latitude: !secret lat
    longitude: !secret long

device_tracker:
  - platform: unifi
    host: !secret host_ip
    site_id: 5vyjbuzt
    verify_ssl: true
    username: !secret unifi_user
    password: !secret unifi_pass
    consider_home: 180
    dont_track_devices: true
    dont_track_wired_clients: true
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false
    ssid_filter:
      - 'WEFi'

# vacuum:
#   - platform: xiaomi_miio
#     host: 10.0.2.167
#     token: YOUR_TOKEN

# Text to speech
# tts:
#   - platform: microsoft
#     api_key: !secret speech_api_key
#     language: en-us
#     gender: Female
#     type: JessaRUS
#     rate: 20
#     volume: -50
#     pitch: high
#     contour: (0, 0) (100, 100)

hue:
  bridges:
    - host: !secret hue_ip

sabnzbd:
  host: !secret host_ip
  port: !secret sab_port
  api_key: !secret sab_api_key
  sensors:
    - 'current_status'
    - 'speed'
    - 'queue_size'
    - 'queue_remaining'
    - 'disk_size'
    - 'disk_free'

sonos:
  media_player:
    hosts: 
      - !secret sonos_playbase_ip
      - !secret sonos_kitchen_front_ip
      - !secret sonos_study_ip
      - !secret sonos_office_ip
      # - !secret sonos_kitchen_back_ip
      # - !secret sonos_living_front_ip
      # - !secret sonos_living_back_ip

ring:
  username: !secret ring_username
  password: !secret ring_password

binary_sensor:
  - platform: ring
  - platform: template
    sensors:
      ring_ringing:
        entity_id: binary_sensor.ring_front_door_ding
        friendly_name: "Front Door Ringing"
        value_template: '{{ states.binary_sensor.ring_front_door_ding.attributes.state == "ringing" }}'
camera:
  - platform: ring

# homeconnect:
#   client_id: !secret homeconnect_client_id
#   client_secret: !secret homeconnect_client_secret

logger:
  default: critical
  logs:
    requests.packages.urllib3.connectionpool: critical
    py.warnings: critical
  #   custom_components.azure_event_hub_new: debug
  #   homeassistant.components.azure_event_hub: debug
#     homeassistant.components.python_script: debug
    # custom_components.homeconnect: debug
    # homeassistant.components.sonos: debug
    # homeassistant.components.media_player.sonos: debug
